version: '3.9'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - queue-net
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/www.emailanalysis.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/www.emailanalysis.uxlivinglab.online/fullchain.pem:ro
      - /etc/letsencrypt/live/www.emailanalysis.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/www.emailanalysis.uxlivinglab.online/privkey.pem:ro
    restart: always
    networks:
      - queue-net
    depends_on:
      - server
networks:
  queue-net:
    driver: bridge